import { GeocodedPlace } from '../types/astro';

export interface CityEntry extends GeocodedPlace {
  aliases?: string[];
}

export const POPULAR_CITIES: CityEntry[] = [
  // --- Telangana Towns & Cities ---
  {
    display_name: 'Korutla (Koratla), Jagtial, Telangana, India',
    city: 'Korutla',
    state: 'Telangana',
    country: 'India',
    latitude: 18.8257,
    longitude: 78.7116,
    timezone: 'Asia/Kolkata',
    aliases: ['koratla', 'korutla mandal', 'jagtial korutla', 'koratla town'],
  },
  {
    display_name: 'Metpally (Metpalli), Jagtial, Telangana, India',
    city: 'Metpally',
    state: 'Telangana',
    country: 'India',
    latitude: 18.8282,
    longitude: 78.5872,
    timezone: 'Asia/Kolkata',
    aliases: ['metpalli', 'metpally mandal', 'jagtial metpally', 'metpalli town'],
  },
  {
    display_name: 'Jagtial (Jagtiyal), Telangana, India',
    city: 'Jagtial',
    state: 'Telangana',
    country: 'India',
    latitude: 18.7963,
    longitude: 78.9167,
    timezone: 'Asia/Kolkata',
    aliases: ['jagtiyal', 'jagtial district'],
  },
  {
    display_name: 'Karimnagar, Telangana, India',
    city: 'Karimnagar',
    state: 'Telangana',
    country: 'India',
    latitude: 18.4386,
    longitude: 79.1288,
    timezone: 'Asia/Kolkata',
    aliases: ['karimnagar town'],
  },
  {
    display_name: 'Nizamabad, Telangana, India',
    city: 'Nizamabad',
    state: 'Telangana',
    country: 'India',
    latitude: 18.6725,
    longitude: 78.0941,
    timezone: 'Asia/Kolkata',
    aliases: ['nizamabad town'],
  },
  {
    display_name: 'Armoor (Armur), Nizamabad, Telangana, India',
    city: 'Armoor',
    state: 'Telangana',
    country: 'India',
    latitude: 18.7885,
    longitude: 78.2917,
    timezone: 'Asia/Kolkata',
    aliases: ['armur'],
  },
  {
    display_name: 'Bodhan, Nizamabad, Telangana, India',
    city: 'Bodhan',
    state: 'Telangana',
    country: 'India',
    latitude: 18.6653,
    longitude: 77.8864,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Kamareddy, Telangana, India',
    city: 'Kamareddy',
    state: 'Telangana',
    country: 'India',
    latitude: 18.3248,
    longitude: 78.3392,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Sircilla, Rajanna Sircilla, Telangana, India',
    city: 'Sircilla',
    state: 'Telangana',
    country: 'India',
    latitude: 18.3846,
    longitude: 78.8028,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Vemulawada, Rajanna Sircilla, Telangana, India',
    city: 'Vemulawada',
    state: 'Telangana',
    country: 'India',
    latitude: 18.4682,
    longitude: 78.8661,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Siddipet, Telangana, India',
    city: 'Siddipet',
    state: 'Telangana',
    country: 'India',
    latitude: 18.1018,
    longitude: 78.8520,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Dharmapuri, Jagtial, Telangana, India',
    city: 'Dharmapuri',
    state: 'Telangana',
    country: 'India',
    latitude: 18.9483,
    longitude: 79.0886,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Raikal, Jagtial, Telangana, India',
    city: 'Raikal',
    state: 'Telangana',
    country: 'India',
    latitude: 18.8783,
    longitude: 78.7883,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Kathlapur, Jagtial, Telangana, India',
    city: 'Kathlapur',
    state: 'Telangana',
    country: 'India',
    latitude: 18.7758,
    longitude: 78.7472,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Mallial, Jagtial, Telangana, India',
    city: 'Mallial',
    state: 'Telangana',
    country: 'India',
    latitude: 18.6942,
    longitude: 78.9667,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Ibrahimpatnam, Jagtial, Telangana, India',
    city: 'Ibrahimpatnam',
    state: 'Telangana',
    country: 'India',
    latitude: 18.8953,
    longitude: 78.5039,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Medipalli, Jagtial, Telangana, India',
    city: 'Medipalli',
    state: 'Telangana',
    country: 'India',
    latitude: 18.7611,
    longitude: 78.6361,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Peddapalli, Telangana, India',
    city: 'Peddapalli',
    state: 'Telangana',
    country: 'India',
    latitude: 18.6167,
    longitude: 79.3833,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Ramagundam (Godavarikhani), Telangana, India',
    city: 'Ramagundam',
    state: 'Telangana',
    country: 'India',
    latitude: 18.7551,
    longitude: 79.5132,
    timezone: 'Asia/Kolkata',
    aliases: ['godavarikhani'],
  },
  {
    display_name: 'Mancherial, Telangana, India',
    city: 'Mancherial',
    state: 'Telangana',
    country: 'India',
    latitude: 18.8679,
    longitude: 79.4639,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Bellampalli, Mancherial, Telangana, India',
    city: 'Bellampalli',
    state: 'Telangana',
    country: 'India',
    latitude: 19.0558,
    longitude: 79.4939,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Mandamarri, Mancherial, Telangana, India',
    city: 'Mandamarri',
    state: 'Telangana',
    country: 'India',
    latitude: 18.9833,
    longitude: 79.4833,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Nirmal, Telangana, India',
    city: 'Nirmal',
    state: 'Telangana',
    country: 'India',
    latitude: 19.0964,
    longitude: 78.3433,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Bhainsa, Nirmal, Telangana, India',
    city: 'Bhainsa',
    state: 'Telangana',
    country: 'India',
    latitude: 19.1912,
    longitude: 77.9620,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Adilabad, Telangana, India',
    city: 'Adilabad',
    state: 'Telangana',
    country: 'India',
    latitude: 19.6641,
    longitude: 78.5320,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Kagaznagar, Asifabad, Telangana, India',
    city: 'Kagaznagar',
    state: 'Telangana',
    country: 'India',
    latitude: 19.3458,
    longitude: 79.4939,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Warangal (Hanamkonda / Kazipet), Telangana, India',
    city: 'Warangal',
    state: 'Telangana',
    country: 'India',
    latitude: 17.9784,
    longitude: 79.5941,
    timezone: 'Asia/Kolkata',
    aliases: ['hanamkonda', 'kazipet'],
  },
  {
    display_name: 'Khammam, Telangana, India',
    city: 'Khammam',
    state: 'Telangana',
    country: 'India',
    latitude: 17.2473,
    longitude: 80.1514,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Kothagudem (Palwancha), Telangana, India',
    city: 'Kothagudem',
    state: 'Telangana',
    country: 'India',
    latitude: 17.5552,
    longitude: 80.6198,
    timezone: 'Asia/Kolkata',
    aliases: ['palwancha', 'bhadradri'],
  },
  {
    display_name: 'Bhadrachalam, Bhadradri Kothagudem, Telangana, India',
    city: 'Bhadrachalam',
    state: 'Telangana',
    country: 'India',
    latitude: 17.6688,
    longitude: 80.8936,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Mahbubnagar, Telangana, India',
    city: 'Mahbubnagar',
    state: 'Telangana',
    country: 'India',
    latitude: 16.7488,
    longitude: 78.0035,
    timezone: 'Asia/Kolkata',
    aliases: ['palamuru'],
  },
  {
    display_name: 'Nalgonda, Telangana, India',
    city: 'Nalgonda',
    state: 'Telangana',
    country: 'India',
    latitude: 17.0575,
    longitude: 79.2684,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Suryapet, Telangana, India',
    city: 'Suryapet',
    state: 'Telangana',
    country: 'India',
    latitude: 17.1439,
    longitude: 79.6239,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Miryalaguda, Nalgonda, Telangana, India',
    city: 'Miryalaguda',
    state: 'Telangana',
    country: 'India',
    latitude: 16.8696,
    longitude: 79.5638,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Jangaon, Telangana, India',
    city: 'Jangaon',
    state: 'Telangana',
    country: 'India',
    latitude: 17.7228,
    longitude: 79.1558,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Sangareddy, Telangana, India',
    city: 'Sangareddy',
    state: 'Telangana',
    country: 'India',
    latitude: 17.6190,
    longitude: 78.0818,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Zaheerabad, Sangareddy, Telangana, India',
    city: 'Zaheerabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.6792,
    longitude: 77.6083,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Vikarabad, Telangana, India',
    city: 'Vikarabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.3370,
    longitude: 77.9048,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Tandur, Vikarabad, Telangana, India',
    city: 'Tandur',
    state: 'Telangana',
    country: 'India',
    latitude: 17.2573,
    longitude: 77.5818,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Gadwal, Jogulamba Gadwal, Telangana, India',
    city: 'Gadwal',
    state: 'Telangana',
    country: 'India',
    latitude: 16.2319,
    longitude: 77.8016,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Wanaparthy, Telangana, India',
    city: 'Wanaparthy',
    state: 'Telangana',
    country: 'India',
    latitude: 16.3624,
    longitude: 78.0628,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Nagarkurnool, Telangana, India',
    city: 'Nagarkurnool',
    state: 'Telangana',
    country: 'India',
    latitude: 16.4856,
    longitude: 78.3142,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Medak, Telangana, India',
    city: 'Medak',
    state: 'Telangana',
    country: 'India',
    latitude: 18.0461,
    longitude: 78.2618,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Huzurabad, Karimnagar, Telangana, India',
    city: 'Huzurabad',
    state: 'Telangana',
    country: 'India',
    latitude: 18.1928,
    longitude: 79.3906,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Hyderabad (Secunderabad / Cyberabad), Telangana, India',
    city: 'Hyderabad',
    state: 'Telangana',
    country: 'India',
    latitude: 17.3850,
    longitude: 78.4867,
    timezone: 'Asia/Kolkata',
    aliases: ['secunderabad', 'cyberabad', 'shamshabad'],
  },

  // --- Andhra Pradesh Towns & Cities ---
  {
    display_name: 'Visakhapatnam (Vizag), Andhra Pradesh, India',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 17.6868,
    longitude: 83.2185,
    timezone: 'Asia/Kolkata',
    aliases: ['vizag', 'waltair'],
  },
  {
    display_name: 'Vijayawada, Andhra Pradesh, India',
    city: 'Vijayawada',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.5062,
    longitude: 80.6480,
    timezone: 'Asia/Kolkata',
    aliases: ['bezawada'],
  },
  {
    display_name: 'Guntur, Andhra Pradesh, India',
    city: 'Guntur',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.3067,
    longitude: 80.4365,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Nellore, Andhra Pradesh, India',
    city: 'Nellore',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.4426,
    longitude: 79.9865,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Kurnool, Andhra Pradesh, India',
    city: 'Kurnool',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 15.8281,
    longitude: 78.0373,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Rajahmundry (Rajamahendravaram), Andhra Pradesh, India',
    city: 'Rajahmundry',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 17.0005,
    longitude: 81.8040,
    timezone: 'Asia/Kolkata',
    aliases: ['rajamahendravaram'],
  },
  {
    display_name: 'Kakinada, Andhra Pradesh, India',
    city: 'Kakinada',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.9891,
    longitude: 82.2475,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Tirupati, Andhra Pradesh, India',
    city: 'Tirupati',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.6288,
    longitude: 79.4192,
    timezone: 'Asia/Kolkata',
    aliases: ['tirumala'],
  },
  {
    display_name: 'Kadapa (Cuddapah), Andhra Pradesh, India',
    city: 'Kadapa',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.4673,
    longitude: 78.8242,
    timezone: 'Asia/Kolkata',
    aliases: ['cuddapah'],
  },
  {
    display_name: 'Anantapur, Andhra Pradesh, India',
    city: 'Anantapur',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.6819,
    longitude: 77.6006,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Eluru, Andhra Pradesh, India',
    city: 'Eluru',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.7107,
    longitude: 81.0952,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Ongole, Andhra Pradesh, India',
    city: 'Ongole',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 15.5057,
    longitude: 80.0499,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Nandyal, Andhra Pradesh, India',
    city: 'Nandyal',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 15.4886,
    longitude: 78.4836,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Machilipatnam (Bandar), Andhra Pradesh, India',
    city: 'Machilipatnam',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.1876,
    longitude: 81.1389,
    timezone: 'Asia/Kolkata',
    aliases: ['bandar'],
  },
  {
    display_name: 'Adoni, Kurnool, Andhra Pradesh, India',
    city: 'Adoni',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 15.6322,
    longitude: 77.2728,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Tenali, Guntur, Andhra Pradesh, India',
    city: 'Tenali',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.2437,
    longitude: 80.6400,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Proddatur, Kadapa, Andhra Pradesh, India',
    city: 'Proddatur',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.7505,
    longitude: 78.5520,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Chittoor, Andhra Pradesh, India',
    city: 'Chittoor',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.2172,
    longitude: 79.1003,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Hindupur, Sri Sathya Sai, Andhra Pradesh, India',
    city: 'Hindupur',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.8289,
    longitude: 77.4919,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Bhimavaram, West Godavari, Andhra Pradesh, India',
    city: 'Bhimavaram',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.5449,
    longitude: 81.5212,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Madanapalle, Annamayya, Andhra Pradesh, India',
    city: 'Madanapalle',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 13.5560,
    longitude: 78.5010,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Guntakal, Anantapur, Andhra Pradesh, India',
    city: 'Guntakal',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 15.1667,
    longitude: 77.3667,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Srikakulam, Andhra Pradesh, India',
    city: 'Srikakulam',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 18.2969,
    longitude: 83.8968,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Vizianagaram, Andhra Pradesh, India',
    city: 'Vizianagaram',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 18.1067,
    longitude: 83.3956,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Dharmavaram, Sri Sathya Sai, Andhra Pradesh, India',
    city: 'Dharmavaram',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 14.4144,
    longitude: 77.7214,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Gudivada, Krishna, Andhra Pradesh, India',
    city: 'Gudivada',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.4410,
    longitude: 80.9926,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Narasaraopet, Palnadu, Andhra Pradesh, India',
    city: 'Narasaraopet',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.2349,
    longitude: 80.0499,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Tadepalligudem, West Godavari, Andhra Pradesh, India',
    city: 'Tadepalligudem',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.8139,
    longitude: 81.5262,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Amaravati (Mangalagiri), Andhra Pradesh, India',
    city: 'Amaravati',
    state: 'Andhra Pradesh',
    country: 'India',
    latitude: 16.5735,
    longitude: 80.3575,
    timezone: 'Asia/Kolkata',
    aliases: ['mangalagiri'],
  },

  // --- Major Pan-Indian Metros & Pilgrimage Centers ---
  {
    display_name: 'New Delhi, Delhi, India',
    city: 'New Delhi',
    state: 'Delhi',
    country: 'India',
    latitude: 28.6139,
    longitude: 77.2090,
    timezone: 'Asia/Kolkata',
    aliases: ['delhi', 'ncr'],
  },
  {
    display_name: 'Mumbai, Maharashtra, India',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.0760,
    longitude: 72.8777,
    timezone: 'Asia/Kolkata',
    aliases: ['bombay', 'thane', 'navi mumbai'],
  },
  {
    display_name: 'Bengaluru (Bangalore), Karnataka, India',
    city: 'Bengaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9716,
    longitude: 77.5946,
    timezone: 'Asia/Kolkata',
    aliases: ['bangalore'],
  },
  {
    display_name: 'Kolkata (Calcutta), West Bengal, India',
    city: 'Kolkata',
    state: 'West Bengal',
    country: 'India',
    latitude: 22.5726,
    longitude: 88.3639,
    timezone: 'Asia/Kolkata',
    aliases: ['calcutta', 'howrah'],
  },
  {
    display_name: 'Chennai (Madras), Tamil Nadu, India',
    city: 'Chennai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 13.0827,
    longitude: 80.2707,
    timezone: 'Asia/Kolkata',
    aliases: ['madras'],
  },
  {
    display_name: 'Ahmedabad, Gujarat, India',
    city: 'Ahmedabad',
    state: 'Gujarat',
    country: 'India',
    latitude: 23.0225,
    longitude: 72.5714,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Pune, Maharashtra, India',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.5204,
    longitude: 73.8567,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Jaipur, Rajasthan, India',
    city: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    latitude: 26.9124,
    longitude: 75.7873,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Lucknow, Uttar Pradesh, India',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 26.8467,
    longitude: 80.9462,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Varanasi (Kashi / Banaras), Uttar Pradesh, India',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 25.3176,
    longitude: 82.9739,
    timezone: 'Asia/Kolkata',
    aliases: ['kashi', 'banaras'],
  },
  {
    display_name: 'Ujjain (Avantika), Madhya Pradesh, India',
    city: 'Ujjain',
    state: 'Madhya Pradesh',
    country: 'India',
    latitude: 23.1765,
    longitude: 75.7885,
    timezone: 'Asia/Kolkata',
    aliases: ['avantika', 'mahakal'],
  },
  {
    display_name: 'Ayodhya, Uttar Pradesh, India',
    city: 'Ayodhya',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 26.7922,
    longitude: 82.1998,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Haridwar, Uttarakhand, India',
    city: 'Haridwar',
    state: 'Uttarakhand',
    country: 'India',
    latitude: 29.9457,
    longitude: 78.1642,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Rishikesh, Uttarakhand, India',
    city: 'Rishikesh',
    state: 'Uttarakhand',
    country: 'India',
    latitude: 30.0869,
    longitude: 78.2676,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Rameswaram, Tamil Nadu, India',
    city: 'Rameswaram',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 9.2876,
    longitude: 79.3129,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Mathura, Uttar Pradesh, India',
    city: 'Mathura',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 27.4924,
    longitude: 77.6737,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Vrindavan, Uttar Pradesh, India',
    city: 'Vrindavan',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 27.5806,
    longitude: 77.7006,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Puri (Jagannath Puri), Odisha, India',
    city: 'Puri',
    state: 'Odisha',
    country: 'India',
    latitude: 19.8135,
    longitude: 85.8312,
    timezone: 'Asia/Kolkata',
    aliases: ['jagannath puri'],
  },
  {
    display_name: 'Amritsar, Punjab, India',
    city: 'Amritsar',
    state: 'Punjab',
    country: 'India',
    latitude: 31.6340,
    longitude: 74.8723,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Chandigarh, Punjab/Haryana, India',
    city: 'Chandigarh',
    state: 'Chandigarh',
    country: 'India',
    latitude: 30.7333,
    longitude: 76.7794,
    timezone: 'Asia/Kolkata',
    aliases: ['mohali', 'panchkula'],
  },
  {
    display_name: 'Indore, Madhya Pradesh, India',
    city: 'Indore',
    state: 'Madhya Pradesh',
    country: 'India',
    latitude: 22.7196,
    longitude: 75.8577,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Bhopal, Madhya Pradesh, India',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    country: 'India',
    latitude: 23.2599,
    longitude: 77.4126,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Nagpur, Maharashtra, India',
    city: 'Nagpur',
    state: 'Maharashtra',
    country: 'India',
    latitude: 21.1458,
    longitude: 79.0882,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Nashik (Trimbakeshwar), Maharashtra, India',
    city: 'Nashik',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.9975,
    longitude: 73.7898,
    timezone: 'Asia/Kolkata',
    aliases: ['nasik', 'trimbakeshwar'],
  },
  {
    display_name: 'Shirdi, Maharashtra, India',
    city: 'Shirdi',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.7645,
    longitude: 74.4762,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Patna, Bihar, India',
    city: 'Patna',
    state: 'Bihar',
    country: 'India',
    latitude: 25.5941,
    longitude: 85.1376,
    timezone: 'Asia/Kolkata',
    aliases: ['patliputra'],
  },
  {
    display_name: 'Gaya (Bodh Gaya), Bihar, India',
    city: 'Gaya',
    state: 'Bihar',
    country: 'India',
    latitude: 24.7914,
    longitude: 85.0002,
    timezone: 'Asia/Kolkata',
    aliases: ['bodh gaya'],
  },
  {
    display_name: 'Guwahati, Assam, India',
    city: 'Guwahati',
    state: 'Assam',
    country: 'India',
    latitude: 26.1445,
    longitude: 91.7362,
    timezone: 'Asia/Kolkata',
    aliases: ['kamakhya'],
  },
  {
    display_name: 'Bhubaneswar, Odisha, India',
    city: 'Bhubaneswar',
    state: 'Odisha',
    country: 'India',
    latitude: 20.2961,
    longitude: 85.8245,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Cuttack, Odisha, India',
    city: 'Cuttack',
    state: 'Odisha',
    country: 'India',
    latitude: 20.4625,
    longitude: 85.8828,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Surat, Gujarat, India',
    city: 'Surat',
    state: 'Gujarat',
    country: 'India',
    latitude: 21.1702,
    longitude: 72.8311,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Vadodara (Baroda), Gujarat, India',
    city: 'Vadodara',
    state: 'Gujarat',
    country: 'India',
    latitude: 22.3072,
    longitude: 73.1812,
    timezone: 'Asia/Kolkata',
    aliases: ['baroda'],
  },
  {
    display_name: 'Rajkot, Gujarat, India',
    city: 'Rajkot',
    state: 'Gujarat',
    country: 'India',
    latitude: 22.3039,
    longitude: 70.8022,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Dwarka, Gujarat, India',
    city: 'Dwarka',
    state: 'Gujarat',
    country: 'India',
    latitude: 22.2442,
    longitude: 68.9685,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Somnath (Veraval), Gujarat, India',
    city: 'Somnath',
    state: 'Gujarat',
    country: 'India',
    latitude: 20.9009,
    longitude: 70.4042,
    timezone: 'Asia/Kolkata',
    aliases: ['veraval'],
  },
  {
    display_name: 'Coimbatore, Tamil Nadu, India',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 11.0168,
    longitude: 76.9558,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Madurai, Tamil Nadu, India',
    city: 'Madurai',
    state: 'Tamil Nadu',
    country: 'India',
    latitude: 9.9252,
    longitude: 78.1198,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Kochi (Cochin), Kerala, India',
    city: 'Kochi',
    state: 'Kerala',
    country: 'India',
    latitude: 9.9312,
    longitude: 76.2673,
    timezone: 'Asia/Kolkata',
    aliases: ['cochin', 'ernakulam'],
  },
  {
    display_name: 'Thiruvananthapuram (Trivandrum), Kerala, India',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    country: 'India',
    latitude: 8.5241,
    longitude: 76.9366,
    timezone: 'Asia/Kolkata',
    aliases: ['trivandrum'],
  },
  {
    display_name: 'Mysuru (Mysore), Karnataka, India',
    city: 'Mysuru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.2958,
    longitude: 76.6394,
    timezone: 'Asia/Kolkata',
    aliases: ['mysore'],
  },
  {
    display_name: 'Hubballi (Hubli / Dharwad), Karnataka, India',
    city: 'Hubballi',
    state: 'Karnataka',
    country: 'India',
    latitude: 15.3647,
    longitude: 75.1240,
    timezone: 'Asia/Kolkata',
    aliases: ['hubli', 'dharwad'],
  },
  {
    display_name: 'Mangaluru (Mangalore), Karnataka, India',
    city: 'Mangaluru',
    state: 'Karnataka',
    country: 'India',
    latitude: 12.9141,
    longitude: 74.8560,
    timezone: 'Asia/Kolkata',
    aliases: ['mangalore'],
  },
  {
    display_name: 'Kalaburagi (Gulbarga), Karnataka, India',
    city: 'Kalaburagi',
    state: 'Karnataka',
    country: 'India',
    latitude: 17.3297,
    longitude: 76.8343,
    timezone: 'Asia/Kolkata',
    aliases: ['gulbarga'],
  },
  {
    display_name: 'Belagavi (Belgaum), Karnataka, India',
    city: 'Belagavi',
    state: 'Karnataka',
    country: 'India',
    latitude: 15.8497,
    longitude: 74.4977,
    timezone: 'Asia/Kolkata',
    aliases: ['belgaum'],
  },
  {
    display_name: 'Raichur, Karnataka, India',
    city: 'Raichur',
    state: 'Karnataka',
    country: 'India',
    latitude: 16.2076,
    longitude: 77.3463,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Ballari (Bellary), Karnataka, India',
    city: 'Ballari',
    state: 'Karnataka',
    country: 'India',
    latitude: 15.1394,
    longitude: 76.9214,
    timezone: 'Asia/Kolkata',
    aliases: ['bellary'],
  },
  {
    display_name: 'Nanded, Maharashtra, India',
    city: 'Nanded',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.1383,
    longitude: 77.3210,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Latur, Maharashtra, India',
    city: 'Latur',
    state: 'Maharashtra',
    country: 'India',
    latitude: 18.4088,
    longitude: 76.5604,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Solapur, Maharashtra, India',
    city: 'Solapur',
    state: 'Maharashtra',
    country: 'India',
    latitude: 17.6599,
    longitude: 75.9064,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Chhatrapati Sambhajinagar (Aurangabad), Maharashtra, India',
    city: 'Aurangabad',
    state: 'Maharashtra',
    country: 'India',
    latitude: 19.8762,
    longitude: 75.3433,
    timezone: 'Asia/Kolkata',
    aliases: ['sambhajinagar', 'aurangabad'],
  },
  {
    display_name: 'Dehradun, Uttarakhand, India',
    city: 'Dehradun',
    state: 'Uttarakhand',
    country: 'India',
    latitude: 30.3165,
    longitude: 78.0322,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Noida, Uttar Pradesh, India',
    city: 'Noida',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 28.5355,
    longitude: 77.3910,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Gurgaon (Gurugram), Haryana, India',
    city: 'Gurgaon',
    state: 'Haryana',
    country: 'India',
    latitude: 28.4595,
    longitude: 77.0266,
    timezone: 'Asia/Kolkata',
    aliases: ['gurugram'],
  },
  {
    display_name: 'Faridabad, Haryana, India',
    city: 'Faridabad',
    state: 'Haryana',
    country: 'India',
    latitude: 28.4089,
    longitude: 77.3178,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Ghaziabad, Uttar Pradesh, India',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 28.6692,
    longitude: 77.4538,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Prayagraj (Allahabad), Uttar Pradesh, India',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 25.4358,
    longitude: 81.8463,
    timezone: 'Asia/Kolkata',
    aliases: ['allahabad'],
  },
  {
    display_name: 'Kanpur, Uttar Pradesh, India',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 26.4499,
    longitude: 80.3319,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Agra, Uttar Pradesh, India',
    city: 'Agra',
    state: 'Uttar Pradesh',
    country: 'India',
    latitude: 27.1767,
    longitude: 78.0081,
    timezone: 'Asia/Kolkata',
  },
  {
    display_name: 'Porbandar, Gujarat, India',
    city: 'Porbandar',
    state: 'Gujarat',
    country: 'India',
    latitude: 21.6417,
    longitude: 69.6293,
    timezone: 'Asia/Kolkata',
  },

  // --- Major International Cities ---
  {
    display_name: 'London, Greater London, United Kingdom',
    city: 'London',
    state: 'England',
    country: 'United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
  },
  {
    display_name: 'New York, New York, United States',
    city: 'New York',
    state: 'New York',
    country: 'United States',
    latitude: 40.7128,
    longitude: -74.0060,
    timezone: 'America/New_York',
    aliases: ['nyc', 'manhattan'],
  },
  {
    display_name: 'San Francisco (Bay Area), California, United States',
    city: 'San Francisco',
    state: 'California',
    country: 'United States',
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: 'America/Los_Angeles',
    aliases: ['san jose', 'silicon valley'],
  },
  {
    display_name: 'Los Angeles, California, United States',
    city: 'Los Angeles',
    state: 'California',
    country: 'United States',
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: 'America/Los_Angeles',
  },
  {
    display_name: 'Chicago, Illinois, United States',
    city: 'Chicago',
    state: 'Illinois',
    country: 'United States',
    latitude: 41.8781,
    longitude: -87.6298,
    timezone: 'America/Chicago',
  },
  {
    display_name: 'Dallas (Plano / Frisco), Texas, United States',
    city: 'Dallas',
    state: 'Texas',
    country: 'United States',
    latitude: 32.7767,
    longitude: -96.7970,
    timezone: 'America/Chicago',
  },
  {
    display_name: 'Houston, Texas, United States',
    city: 'Houston',
    state: 'Texas',
    country: 'United States',
    latitude: 29.7604,
    longitude: -95.3698,
    timezone: 'America/Chicago',
  },
  {
    display_name: 'Seattle, Washington, United States',
    city: 'Seattle',
    state: 'Washington',
    country: 'United States',
    latitude: 47.6062,
    longitude: -122.3321,
    timezone: 'America/Los_Angeles',
  },
  {
    display_name: 'Toronto, Ontario, Canada',
    city: 'Toronto',
    state: 'Ontario',
    country: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: 'America/Toronto',
  },
  {
    display_name: 'Vancouver, British Columbia, Canada',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'Canada',
    latitude: 49.2827,
    longitude: -123.1207,
    timezone: 'America/Vancouver',
  },
  {
    display_name: 'Dubai, United Arab Emirates',
    city: 'Dubai',
    state: 'Dubai',
    country: 'United Arab Emirates',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
  },
  {
    display_name: 'Abu Dhabi, United Arab Emirates',
    city: 'Abu Dhabi',
    state: 'Abu Dhabi',
    country: 'United Arab Emirates',
    latitude: 24.4539,
    longitude: 54.3773,
    timezone: 'Asia/Dubai',
  },
  {
    display_name: 'Doha, Qatar',
    city: 'Doha',
    state: 'Doha',
    country: 'Qatar',
    latitude: 25.2854,
    longitude: 51.5310,
    timezone: 'Asia/Qatar',
  },
  {
    display_name: 'Singapore, Singapore',
    city: 'Singapore',
    state: 'Singapore',
    country: 'Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
    timezone: 'Asia/Singapore',
  },
  {
    display_name: 'Kuala Lumpur, Malaysia',
    city: 'Kuala Lumpur',
    state: 'Federal Territory',
    country: 'Malaysia',
    latitude: 3.1390,
    longitude: 101.6869,
    timezone: 'Asia/Kuala_Lumpur',
  },
  {
    display_name: 'Sydney, New South Wales, Australia',
    city: 'Sydney',
    state: 'New South Wales',
    country: 'Australia',
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: 'Australia/Sydney',
  },
  {
    display_name: 'Melbourne, Victoria, Australia',
    city: 'Melbourne',
    state: 'Victoria',
    country: 'Australia',
    latitude: -37.8136,
    longitude: 144.9631,
    timezone: 'Australia/Melbourne',
  },
  {
    display_name: 'Auckland, New Zealand',
    city: 'Auckland',
    state: 'Auckland',
    country: 'New Zealand',
    latitude: -36.8485,
    longitude: 174.7633,
    timezone: 'Pacific/Auckland',
  },
  {
    display_name: 'Tokyo, Japan',
    city: 'Tokyo',
    state: 'Tokyo',
    country: 'Japan',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
  },
  {
    display_name: 'Paris, France',
    city: 'Paris',
    state: 'Île-de-France',
    country: 'France',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
  },
  {
    display_name: 'Berlin, Germany',
    city: 'Berlin',
    state: 'Berlin',
    country: 'Germany',
    latitude: 52.5200,
    longitude: 13.4050,
    timezone: 'Europe/Berlin',
  },
];

export function searchCitiesLocally(query: string): GeocodedPlace[] {
  const q = query.trim().toLowerCase();
  if (!q || q.length < 1) return [];

  // Exact startsWith gets highest priority
  const matches = POPULAR_CITIES.filter((c) => {
    const cityMatch = c.city.toLowerCase().includes(q);
    const displayMatch = c.display_name.toLowerCase().includes(q);
    const stateMatch = c.state && c.state.toLowerCase().includes(q);
    const countryMatch = c.country.toLowerCase().includes(q);
    const aliasMatch = c.aliases?.some((a) => a.toLowerCase().includes(q));

    return cityMatch || displayMatch || stateMatch || countryMatch || aliasMatch;
  });

  // Sort: Exact startsWith first, then alphabetical
  return matches
    .sort((a, b) => {
      const aStarts = a.city.toLowerCase().startsWith(q) || a.display_name.toLowerCase().startsWith(q);
      const bStarts = b.city.toLowerCase().startsWith(q) || b.display_name.toLowerCase().startsWith(q);
      if (aStarts && !bStarts) return -1;
      if (!aStarts && bStarts) return 1;
      return 0;
    })
    .slice(0, 10);
}
